"""Корректировка графы phone User

Revision ID: 5438c6f5230c
Revises: be0c60f3f565
Create Date: 2023-09-13 21:13:56.082460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5438c6f5230c'
down_revision: Union[str, None] = 'be0c60f3f565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_user_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    op.create_foreign_key('products_user_id_fkey', 'products', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
