"""Корректировка связи

Revision ID: 78c2eeda64e8
Revises: 4408f31a6f2e
Create Date: 2023-09-11 21:56:53.352368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c2eeda64e8'
down_revision: Union[str, None] = '4408f31a6f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_unique_constraint(None, 'users', ['id'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='unique')
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###
