"""Добавление графы name  User

Revision ID: ae032962261f
Revises: 5438c6f5230c
Create Date: 2023-09-13 21:22:17.216169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae032962261f'
down_revision: Union[str, None] = '5438c6f5230c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_user_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=129), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'products', schema='public', type_='foreignkey')
    op.create_foreign_key('products_user_id_fkey', 'products', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
